library(ggplot2)
library(ggthemes)
library(gridExtra)
library(ggpubr)
library(scales)
library(magrittr)
library(dplyr)
library(stringr)
library(tidyr)
library(splitstackshape)
library("data.table")
library(reshape2)
library(RColorBrewer)
library(readr)
library(reshape2)
library(purrr)
library(cowplot)
library(viridis)
library(data.table)

Bess <- read_excel("OCWD Bess Well.xlsx", sheet = "Summary_ALL" ,range = cell_cols("A:E"))

Bess2 <- Bess %>% transmute(.[[1]], .[[4]],.[[5]])
names(Bess2) <- c("Parameter", "Value", "Units" )

Bess2 <- Bess2 %>% group_by(Parameter,Units) %>% summarise (min = min(Value), Avg = mean(Value), max = max(Value), sd = sd(Value))

library(writexl)
write_xlsx(Bess2, path = "OCWD Bess Well Stats.xlsx",   col_names = TRUE, format_headers = TRUE)
